export const CREATE_DETAIL = "CREATE_DETAIL";
export const UPDATE_DETAIL = "UPDATE_DETAIL";
export const DELETE_DETAIL = "DELETE_DETAIL";
export const FETCH_DETAIL = "FETCH_DETAIL";
export const FETCH_DETAILS = "FETCH_DETAILS";

